### ISSUE TITLE
Build: 프로젝트 초기 세팅 및 스타일 설정

### ISSUE THREAD

**Issue by InKyungWoo** [SaveMeMungz/SaveMeMungz-Web#1]
## 💥 이슈 설명

**프로젝트 초기 세팅 완료!!**

## 📚 TO-DO

- [x] github issue, pr 템플릿 추가
- [x] commit convention 추가
- [x] 필요한 라이브러리 설치
  - styled-component, zustand, ~~material ui~~, toastify, prettier, eslint, antd, recharts
- [x] 코드 포맷팅 설정 (prettier, eslint)
- [x] 폴더 구조 변경
- [x] 필요한 assets 추가
- [x] global style 설정 (모바일, 데스크탑 뷰 분리)
  - [x] 기본 페이지 설정, arrow function으로 통일

## 👀 참고 사항

- 빈 폴더는 깃허브에 안올라가서 임시 파일인 .gitkeep 넣어서 push 했습니다. (추후에 삭제하면 되어요!)
- constants에 css 값들 싹 넣고 싶었는데 시간이 오래 걸릴 것 같아 나중에 따로 이슈 파서 들어내겠습니다!
