### ISSUE TITLE
Build: Jira 설정

### ISSUE THREAD

**Issue by InKyungWoo** [SaveMeMungz/SaveMeMungz-Web#12]
## 💥 이슈 설명
Jira 도입 환경 설정

## 📚 TO-DO

- [x] github actions 워크플로우 추가
  - [x] 깃허브 이슈 링크, 내용도 가져오도록 수정
  - [x] 이슈 생성시 활성화된 스프린트 자동 할당
- [x] Jira 이슈 번호 자동 커밋 설정
