### ISSUE TITLE
Test: Jira 연동 테스트

### ISSUE THREAD

**Issue by InKyungWoo** [SaveMeMungz/SaveMeMungz-Web#15]
## 💥 이슈 설명
메인탭 내 남은 화면 UI 퍼블리싱

## 📚 TO-DO

- [ ] 실종 근황 페이지 UI 개발
- [ ] 산책 코스 페이지 UI 개발
  - [ ] 지역 선택 필터 컴포넌트 구현
  - [ ] 보호소 카드 컴포넌트 구현
