### ISSUE TITLE
Feat: 바텀탭 개발 및 폰트 설정

### ISSUE THREAD

**Issue by InKyungWoo** [SaveMeMungz/SaveMeMungz-Web#2]
## 💥 이슈 설명
main 폴더 하위 페이지에 공통으로 적용되는 바텀탭, 헤더 개발

## 📚 TO-DO

- [x] husky, lint 설치 & hook 설정
- [x] pretendard 전역 폰트 설정
- [x] 바텀탭 컴포넌트 구현 + 라우팅
- [x] 홈 헤더 구현
- [x] 전역스타일 & 레이아웃 개선

## 👀 참고 사항

<img width="200" alt="스크린샷 2024-10-03 오전 1 05 49" src="https://github.com/user-attachments/assets/dc671fc4-b57e-43e8-9c7c-d50d6902653d">
