### ISSUE TITLE
Refactor: 홈화면 리팩토링

### ISSUE THREAD

**Issue by InKyungWoo** [SaveMeMungz/SaveMeMungz-Web#26]
## 💥 이슈 설명
- 홈화면 관련 페이지 및 컴포넌트들 리팩토링

## 📚 TO-DO

- [x] github workflow close-issue 트리거 추가
- [x] 루트 하위 components 폴더 생성 및 경로 수정
- [x] CustomTag 컴포넌트 구현
- [x] 홈화면 관련 컴포넌트 리팩토링
  - [x] 공공api 호출 로직 개선 및 utils 분리
  - [x] 멍즈 프로필 카드 컴포넌트 구조 리팩토링, css 수정
  - [x] 매칭 결과 화면 css 수정
