### ISSUE TITLE
Feat: 공통 컴포넌트 개발

### ISSUE THREAD

**Issue by InKyungWoo** [SaveMeMungz/SaveMeMungz-Web#4]
## 💥 이슈 설명
- 공통 컴포넌트 개발 & 기존 요소들 컴포넌트화

## 📚 TO-DO

- [x] 공통 constants 파일 추가
- [x] CustomHeader 컴포넌트 구현
- [x] InfoBanner 컴포넌트 구현
- [x] CustomButton 컴포넌트 구현
