### ISSUE TITLE
Feat: 멍즈 찾기 UI 개발

### ISSUE THREAD

**Issue by CosmicSandBox** [SaveMeMungz/SaveMeMungz-Web#5]
## 💥 이슈 설명
src/app/(main)/home/page.jsx 관련 화면 UI를 제작합니다.

## 📚 TO-DO

- [x] 개의 프로필 박스에 대한 컴포넌트 만들기
- [x] 공공API로 부터 받아올 데이터 넣을 props 부분들 만들기
- [ ] 해당 API들 Zustand로 관리해보기 -> 백엔드랑 상의 후 결정
- [x] 공공 api 사용할 때 api-key .env.local 파일에 넣고 page파일에서 불러와서 사용 + .gitignore에 .env.local 등록하기
- [ ] Constant 사용하는 쪽으로 코드 수정하기
- [ ] API들 API 폴더로 따로 빼기

## 👀 참고 사항
확장자명 js에서 jsx로 바꾸려고 하는데 어떻게 생각하시나요?!
혹시나 Issue Label 잘못달은 것 있으면 말씀해주셔도 됩니다!!
