### ISSUE TITLE
Feat: Splash 화면 구현

### ISSUE THREAD

**Issue by InKyungWoo** [SaveMeMungz/SaveMeMungz-Web#7]
## 💥 이슈 설명

페이지 접속 시 splash 화면을 보여주고 홈으로 전환하는 기능을 구현합니다.

## 📚 TO-DO

- [x] src/app/page.jsx  초기 화면을 splash 화면으로 UI 개발
- [x] 2초 후 홈화면으로 자동 라우팅
- [x] 전환 애니메이션 구현

## 👀 참고 사항
- UX를 고려해서 첫 방문시에만 보여줘야할지 고민,,
